config/fragments: arm64-chromebook: add CONFIG_BACKLIGHT_CLASS_DEVICE
The arm64-chromebook fragment enables CONFIG_DRM_PANEL_VISIONOX_RM69299
but the backlight CONFIG_BACKLIGHT_CLASS_DEVICE is not enabled. The
causes the builds to fail.

  aarch64-linux-gnu-ld: drivers/gpu/drm/panel/panel-visionox-rm69299.o:
    in function `visionox_rm69299_create_backlight':
    undefined reference to `devm_backlight_device_register'

Builds:
  - kbuild-gcc-14-arm64-chromebook
  - kbuild-gcc-14-arm64-chromebook-kcidebug
  - kbuild-gcc-14-arm64-kselftest-16k_pages

Signed-off-by: Ben Copeland <ben.copeland@linaro.org>